CREATE TABLE Nodes (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Type INT NOT NULL,
    Status INT NOT NULL DEFAULT 0,
    DueDate DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL
);

CREATE TABLE Relationships (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    SourceNodeId UNIQUEIDENTIFIER NOT NULL,
    TargetNodeId UNIQUEIDENTIFIER NOT NULL,
    Type INT NOT NULL
);
